---
# Customer
- client_id: customer
  name: customer
  import_certfile: keys/clients/customer.cert
  token_endpoint_auth_method: private_key_jwt
  grant_types: client_credentials
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://customer-control-plane/
  - key: "@type"
    value: ids:datPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: ea3593699acad45973321dbe0011122fa965062ce68c0edcd7a8198d493be91d
# Supplier
- client_id: supplier
  name: supplier
  import_certfile: keys/clients/supplier.cert
  token_endpoint_auth_method: private_key_jwt
  grant_types: client_credentials
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://supplier-control-plane/ #TODO
  - key: "@type"
    value: ids:datPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 89ab21422a70a198bd891d03e165297ce930a766b0c7eee0e24adb5e9bc92115
