---
host: http://ids-daps:4567/
path_prefix: ''
bind_to: 0.0.0.0
allow_origin: "*"
issuer: http://ids-daps:4567/
openid: false
accept_audience: idsc:IDS_CONNECTORS_ALL
default_audience:
- idsc:IDS_CONNECTORS_ALL
app_env: debug
environment: development
access_token:
  expiration: 3600
  algorithm: RS256
id_token:
  expiration: 3600
  algorithm: RS256
front_url: http://ids-daps:4567/
